language: node_js
node_js:
    - stable
install:
    - npm install
cache:
    directories:
        - node_modules
before_script:
    - npm install -g gulp-cli
script:
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: '$GITHUB_TOKEN'
    local_dir: build
    keep_history: true
    on:
        branch: master
env:
    global:
        secure: CsHOxuhxv9hS6Z8dqlucfCckZO14YRdB3MVRwKxXcBsmFJDJTid1j8wHmVwd+qn/OQJJPw3UBJhB9LQuXz9M3gXKCgSy6UH3H8xrE9kf3d56STh+TV4STUphGNpB+Q4zSRGRS6lFxjtHEjygi7wtWg1+GB2yX2K0UJNhDgpd22i/xkMl8Bms4jYj3deIaFKtYb29ZVVyFMBACJS0N44egoaqEYVtHEa97sOCOOGpUfEt3hkb3XJRvyzdEOHu/93mPRzmmWPVUFZf3B1EB9tnUIrpqNciINHsuhCnlkppWOrF/vSiLov+Sdug7/77XJQRfyMJ4F3im/9cQJFlc6vbXaMmEpMgUGQp1uBCdf3pHI6o6vGxGlLyjccEIw6ST6MPF1tpvKhDhCc3ivRnMiDmRiHE/M76tuf7FMAMUZh0/jo1wumMhtZVZo6BtUazRtUe1risZHZMe9NKY3n3URFxlWvx4ETga80lIGynpK6HsAGBkOvTFuXMeRvgHapass0QAsSsW57MqUNv86GhviAXR72DZns/rNkKQ0JHLsPjuqnUmyxsDZ88Y0mM8dClnagnfiqIX8pcyXRRHCcyubSvO1yRRgnQaMDQTMx+PTCCaeEUc1BLQmKzvvv2ARvOQMMHYc+EmYhAxSa87L9BB3OBdp22iqKWpUcUp4rY4nShZNA=
