language: node_js
node_js:
    - stable
install:
    - npm install
cache:
    directories:
        - node_modules
before_script:
    - npm install -g gulp-cli
script:
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: '$GITHUB_TOKEN'
    local_dir: build
    keep_history: true
    on:
        branch: master
env:
    global:
        secure: k89xKKaLr8sr/hV8FBXtAre9PMIZLg3dvVr1SLxoxeCOBfIFptpKL0gh+2PJWOG3cnoVPm+4rk0gnMWZUIY+sgw0cUJ52XlbP3/uwDgCEK2IX6tcyrb0i5rQxO2IP5kJSEQAKibPMY7WLqloyerZvdrsP0SWpZwWLKHol+9KUk8I4TsgeRGSp2zSTKMzu5XKtXb7sQp0b3KsQEFss6xrb1ZZLr9Qszp+eOeKPGvE8cfw0220TvYt/F4sFL5dgeOy3QHC0SE2C6m5Cz7XaJomELVd79l9n36th1EPezxilqP8DXNZSze+kYDTXQOGwYpd/AgQtVBgc7WSZuDnDb5xKjeKO0Th4jaWjQgUnCFJUvgI9mHn9ugZ3h7NjBVKhC58p+awYICQ0Hu9Fis1Mzc/Gp15o08QE/+gs5a0f6XyIMXHG5uAlHtB5JpIpKo4dg4LMGYXc8QvNFzvDW6k7+yCuTg+B/y70CrrIB0VjbEjUP/R/ZXOzamUJGyDuaADpvh2lRYkITBzm4tjUHY5JCoNNcMMEMg0A0sNSwFKa0Vldz27u2Q3cviBqBW4mPgI5oW9S0CUVDc7ZlthiCTCSCTHQ/OCa57aQjCNey7ViVu/yEFIgQ/Slf1LZp8yrecZ/05ht2JkLn2N6yQyuwHAdXJw9Hile52AUmo9H874ZZn1FpU=
